language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
before_install:
  - cpanm --notest --quiet Dist::Zilla Devel::Cover::Report::Coveralls
  - dzil authordeps | cpanm --notest --quiet
  - cpanm --notest --quiet Pod::Coverage::TrustPod WebService::Slack::WebApi
install:
  - dzil listdeps | cpanm --notest --quiet
script:
  - dzil test --release --verbose
  - cover -test
after_success:
  - cover -report coveralls
